Pause between cache update retries

diff --git a/roles/temper-usb/files/temperature b/roles/temper-usb/files/temperature
--- a/roles/temper-usb/files/temperature
+++ b/roles/temper-usb/files/temperature
@@ -13,6 +13,7 @@ CACHEFILE="/tmp/$PROG.cache"
 MAXAGE=55
 LINENUM=1
 RETRYSECS=8
+CACHERETRY=3
 
 # Find out what line number (temperature sensor) we want to report.
 if [ $# == 1 ] && [[ "$1" =~ ^[1-9]$ ]] ; then
@@ -21,8 +22,13 @@ fi
 
 # Update the cache file by running the temperature poller command.
 function update_cache() {
-    $POLLCMD > "$CACHEFILE.tmp" 2>/dev/null
-    mv "$CACHEFILE.tmp" "$CACHEFILE" >/dev/null 2>&1 || rm -f "$CACHEFILE.tmp"
+    if $POLLCMD > "$CACHEFILE.tmp" 2> "$CACHEFILE.err" && \
+        [ -s "$CACHEFILE.tmp" ] ; then
+        mv "$CACHEFILE.tmp" "$CACHEFILE" >/dev/null 2>&1 \
+	    && return 0
+    fi
+    rm -f "$CACHEFILE.tmp"
+    return 1
 }
 
 # Try and get a process lock.
@@ -86,7 +92,16 @@ fi
 
 # Refresh the cache file if it is out of date.
 if [[ "$(($NOW - $MODTIME))" -gt "$MAXAGE" ]] ; then
-    update_cache
+    while : ; do
+        CACHERETRY="$(( CACHERETRY - 1 ))"
+        if update_cache ; then
+            break
+        elif [[ "$CACHERETRY" -le 0 ]] ; then
+            echo "Failed to update cache file." >&2
+	    exit 5
+	fi
+	sleep 1
+    done
 fi
 
 # Print the output results from the cache file.
